/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#d3e4fe",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#002114",
        "outline": "#76777d",
        "primary": "#000000",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#68dba9",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#316bf3",
        "on-tertiary-container": "#069669",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#003ea8",
        "outline-variant": "#c6c6cd",
        "surface-tint": "#565e74",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#85f8c4",
        "surface-container-low": "#eff4ff",
        "on-secondary-fixed": "#00174b",
        "surface": "#f8f9ff",
        "on-tertiary-fixed": "#002114",
        "on-primary-container": "#7c839b",
        "primary-container": "#131b2e",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-surface": "#213145",
        "on-error-container": "#93000a",
        "on-background": "#0b1c30",
        "secondary-fixed": "#dbe1ff",
        "secondary": "#0051d5",
        "on-surface": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "on-surface-variant": "#45464d",
        "background": "#f8f9ff",
        "on-secondary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed-variant": "#005137"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "1.5rem",
        "gutter-dense": "0.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "gutter": "1rem",
        "space-md": "0.75rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "numeric-metric": ["Inter", "sans-serif"],
        "numeric-table": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-xl": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "14px", "fontWeight": "500" }],
        "body-lg": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "numeric-metric": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "numeric-table": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
